### ISSUE TITLE
UndefVarError triggered by err.jl

### ISSUE THREAD

**Issue by gdalle** [cjdoris/PythonCall.jl#100]
Hi there, and thanks for the great alternative to PyCall.jl!
There is a Python function in my code which triggers an `UndefVarError: y not defined` when I try to launch it. I traced it back to this line of the package, where `y` doesn't seem to be defined locally:
https://github.com/cjdoris/PythonCall.jl/blob/f59d58e4eb3d6a0154cf8db5aa54f2fe4d09b39d/src/err.jl#L28
Could it be the cause?

**Comment by cjdoris** [comment]
Thanks that's definitely a bug.

**Comment by cjdoris** [comment]
Fixed on the main branch.
