### ISSUE TITLE
Initialization fails for Julia with DEV in version

### ISSUE THREAD

**Issue by jlapeyre** [cjdoris/PythonCall.jl#106]
```shell
> julia --version
julia version 1.8.0-DEV

> python -m juliacall
Traceback (most recent call last):
  ...
  File "/home/lapeyre/code/github/cjdoris/PythonCall/juliacall/semver.py", line 59, in __init__
    self.parts = tuple(map(int, src))
ValueError: invalid literal for int() with base 10: '0-DEV'
```

PythonCall.jl master branch 05237b2c4

This appears to have been introduced in  EDIT: ~cb207df31d~ the most recent commit.

The following prevents the error:
```python
        elif isinstance(src, str):
            src = src.strip().split('.')
            if len(src) == 3:
                prerel = src[2].split('-')
                if len(prerel) == 2:
                    src[2] = prerel[0]
                    self.prerel = prerel[1]
```
But, this just ignores the prerelease `DEV`. And the version is accepted. Also, the string being processed "1.8.0-DEV" does not include the prerelease number. That is:
```julia
julia> VERSION
v"1.8.0-DEV.1455"
```

**Comment by cjdoris** [comment]
Thanks! I'm actually factoring out the dependency management stuff right now and this will get fixed as part of that
