### ISSUE TITLE
Docstring for dispatched methods 

### ISSUE THREAD

**Issue by henry2004y** [cjdoris/PythonCall.jl#107]
I have a case where I want to dispatch on an imported Python function, for example,

```julia
using PythonCall

mpl = pyimport("matplotlib")
mpl.use("qt5agg")

plt = pyimport("matplotlib.pyplot")

# function doc issue

"What should I do?"
function plt.plot(a::String)
   println("hello multi-dispatch!")
   plt.plot(1:10)
end

plt.plot("Haha!")
```

which returns

```julia
julia> include("test_pythoncall.jl")
ERROR: LoadError: MethodError: no method matching doc!(::Module, ::Py, ::Base.Docs.DocStr, ::Type{Tuple{String}})
Closest candidates are:
  doc!(::Module, ::Base.Docs.Binding, ::Base.Docs.DocStr, ::Any) at /home/local/hongyang/bin/julia-1.7.2/share/julia/base/docs/Docs.jl:226
  doc!(::Module, ::Base.Docs.Binding, ::Base.Docs.DocStr) at /home/local/hongyang/bin/julia-1.7.2/share/julia/base/docs/Docs.jl:226
Stacktrace:
 [1] top-level scope
   @ .../test_pythoncall.jl:10
```

Do you have an idea how to fix it?

**Comment by henry2004y** [comment]
I want to make wrappers over Python functions, as if they are native Julia functions. Since Julia is built upon multiple-dispatch, this is doable in Julia. I've taken advantage of this in my package [here](https://github.com/henry2004y/Vlasiator.jl/blob/master/src/plot/pyplot.jl) as an example. In this way I don't need to come up new names for the wrapper plotting functions. This concept is somehow similar to the plotting recipe system in Plots.jl.

In general, say someone want to make a wrapper over a Python function, this is potentially an issue.

**Comment by cjdoris** [comment]
Like I already said, `plt.plot` is a Python function, it can't be overloaded. This isn't anything to do with `PythonCall`, it's just that you can't add methods to things which aren't Julia functions. In contrast, `PyPlot.plot` _is_ a Julia function (it's some wrapper around `plt.plot`) so can be overloaded.

I suggest you make a function which wraps `plt.plot` and then overload that (which is precisely what `PyPlot.jl` does):
```julia
function plot(args...; kwargs...)
    plt.plot(args...; kwargs...)
end
function plot(x::CustomType; kw...)
    // custom overload
end
```
