### ISSUE TITLE
A direct way to import Julia packages in Python?

### ISSUE THREAD

**Issue by henry2004y** [cjdoris/PythonCall.jl#109]
From the current documentation, it seems like to use any Julia package (even the standard ones), we need to create and modify the [juliacalldeps.json](https://cjdoris.github.io/PythonCall.jl/stable/juliacall/#juliacalldeps.json) file. Are we able to import, e.g. `LinearAlgebra` directly in Python? Or is it possible to use a direct `Pkg.add` call in Python to install the Julia packages?

**Comment by cjdoris** [comment]
`jl.seval("using LinearAlgebra")` does what you want. You don't need to put standard libraries in the deps file.

**Comment by cjdoris** [comment]
The JuliaCall docs could certainly be improved, but some of this stuff is in flux right now anyway.
