### ISSUE TITLE
Highlight the differences with PyCall

### ISSUE THREAD

**Issue by diegozea** [cjdoris/PythonCall.jl#11]
Hi! Thanks for this project. It would be nice if the README could highlight the difference between PythonCall and PyCall, so users can easily decide which package to use; or if both can be used together for particular tasks. Thanks!

**Comment by PallHaraldsson** [comment]
It is documented, in case you missed it. I also reported an issue with using both together, but now it should work (if libpython isn't configured to be different in PyCall).

**Comment by cjdoris** [comment]
As PallHaraldsson says, the documentation contains quite a detailed comparison --- though it needs some improvement.

Both packages can be used together. This is now clarified in the getting started section of the documentation.

**Comment by diegozea** [comment]
Thanks! I have missed it at that point :)
