### ISSUE TITLE
combining juliapkg with juliacall

### ISSUE THREAD

**Issue by phaustin** [cjdoris/PythonCall.jl#111]
I'm having problems getting juliacall to use the julia executable installed in my conda environment with juliapkg.  Specifically, if I create a create and activate an environment called testjulia:
```
mamba create --name testjulia python
conda activate testjulia
pip install juliapkg juliacall
```
and then run the following script:

```
import juliapkg #, juliacall
juliapkg.set_julia_compat("1.7.2")
juliapkg.resolve()
print(juliapkg.executable())
# from juliacall import Main as jl
```

**Comment by cjdoris** [comment]
You're at the bleeding edge, I haven't released JuliaCall with this functionality yet. You can install from the main branch or wait a day or two for me to make a release.

**Comment by phaustin** [comment]
thanks, that's great news (computer died right in the middle of posting that issue).
