### ISSUE TITLE
Support selective import in @py macro `@py from <module> import ...`

### ISSUE THREAD

**Issue by hhaensel** [cjdoris/PythonCall.jl#117]
Currently partial imports, e.g. `@py from os.path import join as py_join` are not supported.

I propose to add an additional method to @py that supports this kind of statements.
I'll submit a PR, which you might consider if you like that feature.

BTW, just recently stumbled across `PythonCall` in the discourse announcements. I think it is a really cool package! 🚀

**Comment by cjdoris** [comment]
As mentioned in #118 this functionality exists with syntax `@py import os.path: join as py_join`.

**Comment by hhaensel** [comment]
Thanks for the feedback. I didn 't know that syntax and has just tried the simplest approach, my bad!
I like your version better than mine, it's closer to the Julia way of imports and therefore can be integrated into begin end clauses.
