### ISSUE TITLE
Setting tuple arguments seems impossible

### ISSUE THREAD

**Issue by gpucce** [cjdoris/PythonCall.jl#119]
Hi, sorry to bother again, probably I am failing to understand something. I can't pass tuple arguments to `jl.func` for any function that needs them.

As a MWE I can't find a way to call:

```
jlCairoMakie.Figure(resolution=(1000, 500))
```

However others things didn't work either. Thank you for any help!

**Comment by cjdoris** [comment]
Aha yes indeed the code to convert tuples relied on some Julia internals which changed in v1.7.

Fixed now. There's a release making its way through now so it should work in 15 minutes.
