### ISSUE TITLE
plt.show()

### ISSUE THREAD

**Issue by PaulSoderlind** [cjdoris/PythonCall.jl#122]
`plt = pyimport("matplotlib.pyplot")` works well and it's easy to create plots. 

However, with `plt.show()` the figure window has to be closed manually in order to use the REPL again. Instead with `plt.show(;block=false)` the figure window is blank and Julia hangs. (Julia 1.7.2, Win 10 64).

Example:
```
plt = pyimport("matplotlib.pyplot")
fig = plt.figure()
plt.plot(1:10)
plt.show()
```

**Comment by cjdoris** [comment]
The behaviour with `plt.show()` is just how matplotlib behaves, even from the Python REPL.

To matplotlib in interactive mode, such as `plt.show(block=false)`, you need to start an event loop to do the rendering in the background. See https://cjdoris.github.io/PythonCall.jl/stable/compat/#Event-loops.

**Comment by PaulSoderlind** [comment]
it seems as if something like this works:
```
PythonCall.event_loop_on(:pyqt5)
plt.ion()

fig1 = plt.figure()
plt.plot(1:10)
plt.show()
...and then more plots
```
