### ISSUE TITLE
Document `pyconvert_add_rule`

### ISSUE THREAD

**Issue by jverzani** [cjdoris/PythonCall.jl#125]
Well, I wanted this to be an "issue", but really I have a request for wee bit of help. I asked this on discourse (https://discourse.julialang.org/t/pythoncall-equivalent-to-pycalls-pytype-mapping/77086) but found no answers.

I want to see if I can use `PythonCall` to replace `PyCall` with `SymPy.jl` and to do so am looking for someway to automatically convert the underlying sympy objects into julia objects (such as Py, though with a type from SymPy.) I think the right approach is `pyconvert_add_rule` but can't seem to get it working. As a test case, my current use of `PyCall::pytype_mapping` to do this is basically: `pytype_mapping(sympy.core.basic.Basic, Sym)`.

**Comment by cjdoris** [comment]
Ah sorry I do hang out on discourse but don't necessarily see everything.

I have now documented `pyconvert_add_rule` here: https://cjdoris.github.io/PythonCall.jl/dev/conversion-to-julia/#py2jl-conversion-custom

You'll need to use PythonCall from the main branch (`pkg> add PythonCall#main`) for now until I make a release, because I changed the function a little before documenting it.

**Comment by jverzani** [comment]
Awesome. Thanks so much!

**Comment by jverzani** [comment]
Sorry to trouble you again, but you could guide me as to why the following fails to convert to `Sym` type of the last line:

```
using PythonCall # [6099a3de] PythonCall v0.6.1 `https://github.com/cjdoris/PythonCall.jl.git#main`
struct Sym{P}
    py::P
end

sympy = pyimport("sympy")
x = sympy.symbols("x")
x.__module__ # Python str: 'sympy.core.symbol'
x.__class__  # ython ManagedProperties: <class 'sympy.core.symbol.Symbol'>

pyconvert_sym(::Type{S}, x::Py) where {S} = PythonCall.pyconvert_return(Sym(x))::S
PythonCall.pyconvert_add_rule("sympy.core.symbol:Symbol", Sym, pyconvert_sym)

x = sympy.symbols("x")
```

**Comment by cjdoris** [comment]
Ah, PythonCall does not automatically convert Python objects to Julia ones when you do things like call Python functions. This differs from PyCall. So you must do one of:
- `pyconvert(Any, sympy.symbols("x"))`
- `pyconvert(Sym, sympy.symbols("x"))`
- `Sym(sympy.symbols("x"))` - this of course doesn't require you to define a pyconvert rule first

Also, as the **Important** paragraph in the documentation for `pyconvert_add_rule` says, you are not allowed to return anything which references `x` from your conversion rule. So you must return `Sym(Py(x))` or add an inner constructor like `Sym(x) = new(Py(x))` to `Sym`.

**Comment by jverzani** [comment]
Thanks for the clarification. Most appreciated!
