### ISSUE TITLE
LaTeXStrings

### ISSUE THREAD

**Issue by PaulSoderlind** [cjdoris/PythonCall.jl#127]
This crashes: `plt.title(L"\cos x")` with a message starting with `ERROR: Python: TypeError: __str__ returned non-string`

Instead, this works: `plt.title(String(L"\cos x"))`

Is some kind of conversion planned?

**Comment by cjdoris** [comment]
Ah thanks, that's a bug. Will fix tomorrow.

**Comment by cjdoris** [comment]
Fixed on main.
