### ISSUE TITLE
How to convert a Pandas DataFrame to Julia one without copy?

### ISSUE THREAD

**Issue by ShuhuaGao** [cjdoris/PythonCall.jl#135]
In Python 3.9:
```python
import pandas as pd
import numpy as np

from juliacall import Main as jl

pd_df = pd.DataFrame({'Name': ['Tom', 'nick', 'krish', 'jack'],
                      'Age': [20, 21, 19, 18]})
jl.seval("using DataFrames")
jl_df = jl.DataFrame(pd_df)
jl_df[1, 2] = -100
pd_df.iloc[0, 1]  # still 20
```

Since `PythonCall.PyPandasDataFrame` is compatible with Table.jl and Julia DataFrame's [constructor](https://dataframes.juliadata.org/stable/lib/types/#DataFrames.DataFrame) does not copy a table by default, how to explain the above behaviour? Is there any way to avoid data copying?

**Comment by cjdoris** [comment]
Indeed accessing columns of a `PyPandasDataFrame` is currently a copying operation. That whole functionality isn't very well developed so far - but contributions are welcome.

**Comment by cjdoris** [comment]
The latest release now uses no-copy views of columns where possible, so your above example mutates `pd_df` as desired.
