### ISSUE TITLE
fail to display inside vscode/jupyter notebook

### ISSUE THREAD

**Issue by Roger-luo** [cjdoris/PythonCall.jl#141]
Hi I'd like to use PythonCall for matplotlib in Julia, but I realize this package seems not displaying the picture in vscode or jupyter notebook but will instead open a window if used on laptop.

On the other hand, `plt.figure()` creates an empty plot in vscode, but it won't change after I plot anything. It would be nice if this package could work with jupyter notebook and vscode

**Comment by Roger-luo** [comment]
It seems the seaborn example in README works, but not for `matplotlib.pyplot.plot`, e.g the following code doesn't plot anything in a jupter notebook

```
plt.plot(rand(100))
```

for PyPlot, there is an option to set the plotting inline for jupter notebook, I'm wondering if there is something similar for `PythonCall`?

**Comment by cjdoris** [comment]
Does this work?
```julia
plt.plot(stuff.....)
plt.gcf()
```

**Comment by cjdoris** [comment]
PythonCall used to add a hook to IJulia to display any open plots after executing a cell, but it got removed during a reshuffle. The above incantation returns the current figure though, which PythonCall knows how to display.

**Comment by Roger-luo** [comment]
Yes this works!

**Comment by stevengj** [comment]
PythonPlots.jl adds this hook, too.
