### ISSUE TITLE
docstring method for Base.Docs.doc(::Py)

### ISSUE THREAD

**Issue by stevengj** [cjdoris/PythonCall.jl#147]
It might be nice to make the Julia help fetch the Python docstrings if available?

Something like this: https://github.com/JuliaPy/PyCall.jl/blob/2728e20162db3c90198e2828c40e675924c73528/src/PyCall.jl#L260-L268

**Comment by cjdoris** [comment]
I already overloaded `Docs.getdoc` so `help> pybuiltins.int` works, for example. But I've just added an overload for `Docs.doc` too.

**Comment by icweaver** [comment]
Yayy docstrings! 🌈

![Screenshot_2022-04-21_06-38-32](https://user-images.githubusercontent.com/25312320/164441070-1a940630-08c1-4993-9053-047b00fb3b64.png)

**Comment by CarloLucibello** [comment]
can we get a new release with this feature?

**Comment by cjdoris** [comment]
I've just updated it so the docstring is rendered as a code block. It's not especially pretty, but at least it preserves the formatting of the docstring.

![image](https://user-images.githubusercontent.com/1844215/169667003-9d67fd94-d8e7-48e6-a032-8290cbef9fe7.png)

There are some breaking changes on main, so I'm not rushing into another release, but it won't be long.
