### ISSUE TITLE
missing haskey, get, etcetera?

### ISSUE THREAD

**Issue by stevengj** [cjdoris/PythonCall.jl#148]
If I have a Python dictionary object or similar:
```jl
julia> d = pyeval("{'foo': 1, 'bar': 2}", Main)
Python dict: {'foo': 1, 'bar': 2}
```
it would be nice to be able to use `haskey(d, x)` (by checking whether `PyObject_GetItem` returns `NULL`), `get(d, x, default)` (similar to [this](https://github.com/JuliaPy/PyCall.jl/blob/2728e20162db3c90198e2828c40e675924c73528/src/PyCall.jl#L764-L772)), etcetera.

Maybe  call it `pyhasitem` if you don't want to overload `haskey`.  You already have a 2-arg `pygetitem`, so you could add a 3-arg version instead of overloading `get`.  (Though I'm not sure what's wrong with overloading `haskey` and `get`, since you already overload `getindex`.)

**Comment by stevengj** [comment]
It works to wrap `d` in `PyDict{Any,Any}(d)`, of course.

**Comment by cjdoris** [comment]
OK I've added `pyhasitem`, 3-arg `pygetitem`. I'm a little wary of this, as I try to stick to the Python API and these don't exist, but they are logical analogues of `pyhasattr` and `pyhasitem`.

Have used them to implement `get`, `get!` and `haskey`.

**Comment by stevengj** [comment]
Thanks !
