### ISSUE TITLE
pyisnothing function?

### ISSUE THREAD

**Issue by stevengj** [cjdoris/PythonCall.jl#149]
Seems pretty common to check if something is `None` in Python, but it is a bit awkward (and probably suboptimal) to check `pyconvert(Bool, object == Py(nothing))`.  (Since `None` is a singleton object in Python, you can just check pointer equality.)

**Comment by cjdoris** [comment]
You can already do one of:
```julia
pyis(x, pybuiltins.None)  # 1ns
@py x === None  # 1ns
pyis(x, nothing)  # 20ns
```
