### ISSUE TITLE
ispynull

### ISSUE THREAD

**Issue by stevengj** [cjdoris/PythonCall.jl#151]
Sometimes it is helpful to check whether we have a NULL python object, created via `PythonCall.pynew()`, e.g. to check if something has been initialized yet.  (PyPlot needs this for lazy module loading, for example.)  It might be nice to have a function like:
```jl
ispynull(x::Py) = PythonCall.getptr(x) == PythonCall.C.PyNULL
```
since this otherwise requires you access PythonCall internals.

**Comment by cjdoris** [comment]
Already exists: https://cjdoris.github.io/PythonCall.jl/stable/pythoncall/#PythonCall.pyisnull
