### ISSUE TITLE
Docs: how to use CondaPkg from PythonCall?

### ISSUE THREAD

**Issue by sairus7** [cjdoris/PythonCall.jl#152]
Docs says: https://cjdoris.github.io/PythonCall.jl/stable/pythoncall/#python-deps

> If your project requires any Python packages, add a CondaPkg.toml file to your project specifying what you need. Alternatively use CondaPkg.add() to add dependencies from the REPL.

But how can I access CondaPkg itself from a project using PythonCall? I've tried `CondaPkg`, `PythonCall.CondaPkg` with no success, and had to add it separately to my project: `add CondaPkg`, should it be stated in docs?

**Comment by CaiYitao** [comment]
If I understand your question, you can do

step 1  go to your project in terminal
```
cd your_project 
```
step 2      open julia  (mac command)
```
%   julia  
```
step 3   now you are in julia repl ,  
```julia
using CondaPkg
```
if it is not installed , REPL will prompt an installation. 

after installed CondaPkg,   then ```using CondaPkg```
step 4   press"]"  in the REPL  to access Pkg and activate this project;
```
activate . 
```
Now you are in the project. 
you can add python package with
```
conda add your_python_package
```
last step
```
conda resolve
```
then you are good to go to the pluto notebook in this project
and using these python package like this
<img width="635" alt="image" src="https://user-images.githubusercontent.com/65641330/163196203-2f59f6fd-6d30-456f-b9ce-d949dc637103.png">
<img width="608" alt="image" src="https://user-images.githubusercontent.com/65641330/163196278-7e0dc30d-2bda-42f6-80f0-1ec53e1d4c4e.png">

**Comment by icweaver** [comment]
Oh neat just saw this usage in another [issue](https://github.com/cjdoris/PythonCall.jl/pull/159#issuecomment-1100652072): `PythonCall.C.CondaPkg`

**Comment by cjdoris** [comment]
There's no guarantee `PythonCall.C.CondaPkg` won't be renamed in the future. Just add `CondaPkg` yourself.
