### ISSUE TITLE
How to define python function from Julia side

### ISSUE THREAD

**Issue by chengchingwen** [cjdoris/PythonCall.jl#156]
Is there any way to define python function from Julia side? or something equivalent to `PyCall.@py_str`that can run arbitrary python code from Julia?

**Comment by icweaver** [comment]
I had a [similar question](https://github.com/cjdoris/PythonCall.jl/discussions/91) a little bit ago, and I think the main takeaway was to just do something like this:

```julia
julia> using PythonCall

julia> @pyexec """
       global double
       def double(s):
           return s * 2
       """
julia> double(s) = @pyeval("double")(s)
double (generic function with 1 method)

julia> double("hello")
Python str: 'hellohello'
```

**Comment by chengchingwen** [comment]
Great, thanks!

**Comment by CarloLucibello** [comment]
This is a bit hard to discover, it should be given more prominence in the docs
