### ISSUE TITLE
using functions ending with ! in juliacall

### ISSUE THREAD

**Issue by gpucce** [cjdoris/PythonCall.jl#158]
I used to use `juliacall.using` to rename function ending with ! to be ending with ___ and so acceptatble in python how can I do it now that using is not there anymore?

**Comment by cjdoris** [comment]
Yeah sorry, I'm trying to make the API smaller, so removed that along with some other things.

For the special case of functions ending with `!` you can replace it with `_b` (for "bang"), so for example `juliacall.Base.push_b` is `Base.push!`.

In general, you can use `getattr` to get Julia properties whose names are not valid Python identifiers, such as `getattr(juliacall.Base, "push!")` or `getattr(juliacall.Base, "+")`.
