### ISSUE TITLE
Reloading code

### ISSUE THREAD

**Issue by TLipede** [cjdoris/PythonCall.jl#17]
Hi there, 

Just wondering - is there a way to reload the code from a Python script without restarting the current Julia session?

Thanks in advance! :)

**Comment by cjdoris** [comment]
Sorry I don't understand - how are you loading the Python script in the first place?

**Comment by TLipede** [comment]
Never mind, found a solution with:

```python
importlib = pyimport("importlib")
importlib.reload(somemodule)
```
