### ISSUE TITLE
Bug when 1.6-DEV installed

### ISSUE THREAD

**Issue by PallHaraldsson** [cjdoris/PythonCall.jl#174]
FYI, I had older julicall version, that apparently had downloaded Julia 1.7.2 already but then some different error. I got the latest juliacall with pip3:

```
$ python3.6
Python 3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from juliacall import Main as jl
[juliapkg] Locating Julia ^1.6
[juliapkg] WARNING: You have Julia None installed but ^1.6 is required.
[juliapkg]   It is recommended that you upgrade Julia or install JuliaUp.
[..]
[juliapkg] Verifying download
[juliapkg] Installing Julia 1.7.2 to /home/pharaldsson_sym/miniconda3/julia_env/pyjuliapkg/install
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/juliacall/__init__.py", line 101, in <module>
    init()
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/juliacall/__init__.py", line 59, in init
    CONFIG['exepath'] = exepath = juliapkg.executable()
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/juliapkg/deps.py", line 288, in executable
    resolve()
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/juliapkg/deps.py", line 240, in resolve
    exe, ver = find_julia(compat=compat, prefix=STATE['install'], install=True, upgrade=True)
  File "/home/pharaldsson_sym/.local/lib/python3.6/site-packages/juliapkg/find_julia.py", line 88, in find_julia
    assert pr_ver is not None
AssertionError
```

**Comment by PallHaraldsson** [comment]
Now I have 1.7.0 (not 1.7.2, should matter), and no longer 1.6-DEV in PATH, and I still get similar or identical error/behavior:

"WARNING: You have Julia None installed but ^1.6 is required." I suppose it's not looking at the PATH, rather some hardcoded location?

**Comment by cjdoris** [comment]
You can ignore that warning, it was being printed by mistake. I've fixed it.

That AssertionError in the original post is bad though. Maybe your anti-virus quarantined the Julia executable?

**Comment by PallHaraldsson** [comment]
I have no anti-virus, I'm on Linux...

**Comment by cjdoris** [comment]
Still having this issue or can I close it?

**Comment by PallHaraldsson** [comment]
In short I believe you can close. I didn't test the same config, e.g. no longer have Python 3.6 after update of Ubuntu.

I wrote a lot here, about testing both Example 1 and 2, with my current config, and Matplotlib part of docs could be improved since unclear, but then the web browser crashed...

**Comment by cjdoris** [comment]
Ok I'll close this thanks.

Feel free to open more issues about documentation and the like. It helps me a lot of issues are about a single thing, so if you have N things to discuss then it's best to open N issues. Thanks.
