### ISSUE TITLE
Configure julia options

### ISSUE THREAD

**Issue by dpinol** [cjdoris/PythonCall.jl#184]
Hi,
with pyjulia it's possible to configure some julia options (see https://github.com/JuliaPy/pyjulia/blob/master/src/julia/options.py#L79)
Is it possible with PythonCall?
If not, I'm willing to create a PR if somebody could give me any hint on how to integrate it

related to https://github.com/cjdoris/PythonCall.jl/issues/73

**Comment by cjdoris** [comment]
No, those options are not currently supported, but a PR to implement some would be welcome.

I guess you'd need to do something like this: https://github.com/JuliaPy/pyjulia/blob/56a739126d3fed0d24e548069ff216fea78fbe1b/src/julia/libjulia.py#L330

It would go just above here: https://github.com/cjdoris/PythonCall.jl/blob/6c07d4e4eadb8706b15c5a6fcde9efe116982c3f/pysrc/juliacall/__init__.py#L80

Were there particular options you had in mind?

I think for now use environment variables to set the options, such as `PYTHON_JULIACALL_COMPILE=min`. There isn't any other config mechanism in JuliaCall right now.

**Comment by dpinol** [comment]
Cool, I'm working on it. Cheers!
