### ISSUE TITLE
Juliacall: How to close/end julia session?

### ISSUE THREAD

**Issue by casparvitch** [cjdoris/PythonCall.jl#187]
Hiya,

Great package! Is there any way to close the Julia session from python?
I want to get some memory back. 
There are probably other ways to do it but the simplest Main.exit() crashed the python process that called it.

Cheers

**Comment by cjdoris** [comment]
Hmm, not as far as I know. I don't know if the Julia C API even has a function to stop the interpreter.

**Comment by cjdoris** [comment]
I'm afraid this is not possible - the Julia C API does not provide a way to stop the interpreter other than exiting the process.
