### ISSUE TITLE
Can not use pip package although conda status correct

### ISSUE THREAD

**Issue by jakubMitura14** [cjdoris/PythonCall.jl#198]
I posted it also on discourse in https://discourse.julialang.org/t/can-not-use-pip-package-although-conda-status-correct/84155
Hello I am using PythonCall and I want to use library simpleitk, (in pure python it always works it is well established package) I added it to Conda.toml all installs but I am unable to load it using pyimport, any help would be higly appriciated!

```
CondaPkg Status /home/jakub/projects/MedPipe3D.jl-1/CondaPkg.toml
Packages
  itk v5.2.0
  monai v0.9.0
  python v3.9.13 (>=3.5,<4)
  seaborn v0.11.2
  simpleitk v2.1.0
Channels
  anaconda
  conda-forge
Pip packages
  simpleitk v2.1.0

(MedPipe3D) pkg> conda resolve
    CondaPkg Dependencies already up to date

julia> pyimport("simpleitk")
ERROR: Python: ModuleNotFoundError: No module named 'simpleitk'
Python stacktrace: none
Stacktrace:
 [1] pythrow()
   @ PythonCall ~/.julia/packages/PythonCall/XgP8G/src/err.jl:94
 [2] errcheck
   @ ~/.julia/packages/PythonCall/XgP8G/src/err.jl:10 [inlined]
 [3] pyimport(m::String)
   @ PythonCall ~/.julia/packages/PythonCall/XgP8G/src/concrete/import.jl:11
 [4] top-level scope
   @ ~/projects/MedPipe3D.jl-1/src/playground.jl:15

julia> 

```

my CondaPkg.toml

```
channels = ["anaconda", "conda-forge"]

[deps]
itk = ""
seaborn = ""
simpleitk = ""
python = ">=3.5,<4"
monai = ""

[pip.deps]
simpleitk = ""


```

**Comment by cjdoris** [comment]
The module is called SimpleITK (case sensitive). This works for me: `pyimport("SimpleITK")`.

Also you have simpleitk as both a conda and a pip dependency. You only need one - I'm not sure if weirdness occurs if you install both.
