### ISSUE TITLE
https://cjdoris.github.io/PythonCall.jl not updated to 0.9.3?

### ISSUE THREAD

**Issue by dpinol** [cjdoris/PythonCall.jl#203]
Is https://cjdoris.github.io/PythonCall.jl updated to 0.9.3?
It does not appear in the list of versions not the release notes

thanks

**Comment by cjdoris** [comment]
Good spot thanks, indeed the latest version there is 0.9.1. I'll take a look.

**Comment by cjdoris** [comment]
The problem appears to have fixed itself with yesterday's release. Phew!
