### ISSUE TITLE
Need a new python release: `juliacall` is broken with default (macOS?) Julia installation

### ISSUE THREAD

**Issue by moble** [cjdoris/PythonCall.jl#204]
This problem is fixed in the current `main` branch (by commit 1126b56159ab746b646e3b894cf56fe0bcbb1c19), but has not propagated out to the package on PyPI.

For some reason, the official Julia installer (at least on macOS) creates a symlink to the `julia` executable in `/usr/local/bin`, but does not add anything to `/usr/local/lib`.  Unfortunately, the current PyPI version of `juliacall` ends up looking for the latter directory and dying when it isn't there:
```
ERROR: could not load library "/usr/local/bin/../lib/julia/sys.dylib"
dlopen(/usr/local/bin/../lib/julia/sys.dylib, 0x0006): tried: '/usr/local/bin/../lib/julia/sys.dylib' (no such file)
```
I can verify that installing the more recent commit works:
```bash
python -m pip install git+https://github.com/cjdoris/PythonCall.jl.git@1126b561
```

**Comment by cjdoris** [comment]
Your wish is my command :)

**Comment by moble** [comment]
Thanks!
