### ISSUE TITLE
juliacall and PythonCall versions can get out of sync

### ISSUE THREAD

**Issue by amilsted** [cjdoris/PythonCall.jl#206]
It seems like sometimes juliacall does not request the PythonCall version that matches its own version.

Currently `import juliacall` appears to grab the latest version of PythonCall for julia. If e.g. PythonCall gets a version bump after I did `pip install juliacall`, the import will fail because juliacall grabs the latest PythonCall and its version will not match the older juliacall.

Btw, the error message for a version mismatch is currently not very easy to interpret (it's clear there is a version mismatch, but not clear what packages/tools have mismatched versions).

**Comment by amilsted** [comment]
The Project.toml in the project folder generated for juliacall (`.../julia_env/`) uses the caret specifier, rather than `=`, e.g.
```
[compat]
PythonCall = "^0.9.3"
```

**Comment by cjdoris** [comment]
Good spot! It was [simple to fix](https://github.com/cjdoris/PythonCall.jl/commit/bb5ff0e6489abb20d4f6478cf6d6320899f548f6)! (Though it surfaced a bug in juliapkg which I also fixed.)

Future releases won't have this problem. Until then, just ensure you're on v0.9.4. Thanks!
