### ISSUE TITLE
Resolve sometimes too eager to download package metadata and trigger updates

### ISSUE THREAD

**Issue by amilsted** [cjdoris/PythonCall.jl#209]
It seems to be typical for juliacall and PythonCall/CondaPkg to attempt package updates every time they are loaded by default. For example, loading juliacall seems to always attempt to `add PythonCall` even if it is already present, which can trigger registry and dependency updates.

I know there is an "offline" mode that turns off this behavior by completely turning off package installation/updates completely, but I'm wondering if there could be an option in between.

Basically, if the python and julia packages needed are already correctly installed, I want loading juliacall and PythonCall to work (by default) like a normal `import` or `using` statement - e.g. no calls to `Pkg.add()` from juliacall/juliapkg and no calls to `pip install` from PythonCall/CondaPkg and no internet connection required.

Only if packages are missing, or we don't have the right versions, do I want to probe conda/julia registries. I'm pretty sure this is possible for juliacall/juliapkg, but less sure about CondaPkg/pip.

This would speed up loading of juliacall in python and julia packages that use PythonCall/CondaPkg whenever required julia/python dependencies are already properly installed without the user having to manually switch to offline mode.

**Comment by cjdoris** [comment]
What you've described is the intended behaviour for both packages. If they are installing things every time, it's a bug. Please post a MWE.

**Comment by amilsted** [comment]
Oh, okay! I will make sure I wasn't imagining things and then post an MWE if I can.

**Comment by amilsted** [comment]
So it looks like every time I `import juliacall` from a fresh kernel in a conda environment, I get a full resolve in juliapkg, along with a log message from [this line ](https://github.com/cjdoris/pyjuliapkg/blob/77059a0fd807ae07fe1941314fa40777f62390c5/src/juliapkg/deps.py#L126). This is on mac OS.

**Comment by cjdoris** [comment]
I have just released a new version of pyjuliapkg with (hopefully) a more accurate way to determine if the environment has changed. I'm pretty sure it will solve the issue you're having. Please upgrade pyjuliapkg and try again, it will resolve dependencies the first time, but should skip each time after.

**Comment by amilsted** [comment]
Thanks @cjdoris! The new pyjuliapkg indeed no longer does a full resolve every time in my case. I will close this issue and open another if I see any further issues.

**Comment by cjdoris** [comment]
Great!
