### ISSUE TITLE
Error when trying to display a figure from GLMakie through juliacall

### ISSUE THREAD

**Issue by findmyway** [cjdoris/PythonCall.jl#212]
Hi,

I'd like to call Julia code from python to display some interactive figures. MWE:

```
In [1]: from juliacall import Main as jl

In [2]: jl.seval("using GLMakie")

In [3]: jl.Figure()
Out[3]: Figure()

In [4]: f = jl.scatter(jl.rand(2,5))

In [5]: jl.display(f)
Out[5]: GLMakie.Screen(...)
```

A new Makie window shows up. But nothing in it. And after a while

![image](https://user-images.githubusercontent.com/5612003/185089526-003d1e3f-f408-4f50-aada-0d1c35cd8fd2.png)

Any idea how to make it work?

**Comment by cjdoris** [comment]
My guess is that, since Make is interactive, plotting happens asynchronously. Unfortunately, Julia's event loop only runs while you're actually running Julia code - once you're back in Python it stops.

Maybe calling `jl.yield()` several times from the prompt will work?

**Comment by findmyway** [comment]
Thanks!

**Comment by cjdoris** [comment]
BTW I'm about to release a new version which has a function `juliacall.interactive()` which runs the Julia event loop in the background of the Python REPL. I don't know it will work in IPython, I imagine not.

Also, you should probably put a `time.sleep(0.001)` in that loop I suggested above, so as not to thrash your CPU.
