### ISSUE TITLE
Width & height info of the terminal is not passed to the Julia side?

### ISSUE THREAD

**Issue by findmyway** [cjdoris/PythonCall.jl#216]
When displaying some custom julia struct in IPython, the string output is wrapped. But when I try `jl.display` instead, the struct is displayed correctly as expected.

I'm wondering what we can do to make the printing work as the same in Julia REPL.

**Comment by cjdoris** [comment]
I've thought about this before, there is no generic method to get the display size of a Python file object, so this can't be solved in general.

However, as a special case, we could check if the file object is actually stdout or stderr, and if so use its display size.

**Comment by cjdoris** [comment]
Actually I'm not sure what you mean. Can you give me an example?
