### ISSUE TITLE
Security update (for all supported Python versions)

### ISSUE THREAD

**Issue by PallHaraldsson** [cjdoris/PythonCall.jl#230]
https://pythoninsider.blogspot.com/2022/09/python-releases-3107-3914-3814-and-3714.html

I noticed:
https://github.com/JuliaPackaging/Yggdrasil/pull/5650

I didn't look into how you download Python, but if you use that, I suggest upgrading to that version (when that PR is merged).

Conversely for Python users, you download Julia, and wants to download latest Julia, how do you do that? Could it or should it use juliaup?

**Comment by cjdoris** [comment]
Python is installed with Conda by default, so the version the user gets it out of my hands, but will typically be the latest version, or the latest in a minor series.

Julia is installed by JuliaUp if the user has it installed, or else it is downloaded directly and installed into a environment-specific location.

**Comment by PallHaraldsson** [comment]
You mean CondaPkg (mamba)?

I tried it, though directly, and it gets me 3.8.13, even though 3.8.14 is the secure version. I see:

>Anaconda supports Python 3.7, 3.8, 3.9 and 3.10. The current default is Python 3.9.

Not sure why I didn't get 3.9, which is likely also behind, and I see 3.10.6 not the secure 3.10.7, which would be preferred, unless I missed something, there seem to be many channels, and not sure if you should use some other.

https://anaconda.org/search?q=python

https://anaconda.org/conda-forge/python

**Comment by cjdoris** [comment]
PythonCall installs Python from the conda-forge channel, which is currently on v3.10.6. I guess it takes time for them to package it up.

**Comment by PallHaraldsson** [comment]
I'm not sure what's taking them so long, but do you know if it's possible to get rc2 through conda (otherwise I believe you can use it or any version manually, and bypass conda). Also of interest:

https://peps.python.org/pep-0594/

https://peps.python.org/pep-0623/
