### ISSUE TITLE
Support alternative CPyton e.g. register-based?

### ISSUE THREAD

**Issue by PallHaraldsson** [cjdoris/PythonCall.jl#242]
I'm mostly letting you know such exists, 5% faster, and we're not dependent on Python for speed (though it's always better). Maybe it will be upstreamed eventually.

https://github.com/faster-cpython/ideas/issues/485#issuecomment-1301462011
>this 3.10 fork is API and ABI compatible with CPython

https://github.com/zq1997/RegCPython
https://dl.acm.org/doi/10.1145/3568973

It's not high-priority to support it, some other alternatives might also be worthwhile, PyPy and Pythran, but that one might be more compatible. At least you could consider it as an opt-in.

**Comment by cjdoris** [comment]
PythonCall is very much tied to CPython - but if some other implementation is ABI compatible with it then swapping should be easy - as simple as specifying a different libpython.

On the other hand supporting PyPy and other implementations would be significant effort, but possible.

Personally, I'm never going to make that effort, so it would be up to some other keen contributor.
