### ISSUE TITLE
How to install julia 1.7.0 with juliacall 0.4.3?

### ISSUE THREAD

**Issue by 943fansi** [cjdoris/PythonCall.jl#246]
I am completely unfamiliar with Julia. Now there is a 1.8.2 version of `Julia` in the `PythonCall` directory. I want to use 1.7.0 version of `Julia`. How do I operate? Can I reinstall `JuliaCall` and specify the version of `Julia`?

**Comment by cjdoris** [comment]
Julia dependencies are managed by [`juliapkg`](https://github.com/cjdoris/pyjuliapkg). I recommend reading the README to understand how it works.

You can run something like `juliapkg.require_julia("=1.7.0")` to specify a particular version, or `juliapkg.require_julia("~1.7.0")` to allow any `1.7.*` version. Then restart Python and it will get a compatible version of Julia for you.

If you work in multiple virtual environments (or conda environments) you'll need to do this in each one or else you'll get the default version.

Alternatively, if you have installed Julia yourself already and want to use that, set the environment variable `PYTHON_JULIAPKG_EXE` (see the README).

Why do you need Julia 1.7 anyway? Julia is backwards compatible, so 1.8.2 should work fine.

**Comment by 943fansi** [comment]
Thanks for your reply. The project is opened at [https://github.com/markNZed/ARTimeNAB.jl](https://github.com/markNZed/ARTimeNAB.jl). I used 1.8.2 version and got an error,

**Comment by cjdoris** [comment]
It's weird that the package requires 1.7.0 but ok! Is it working for you now?
