### ISSUE TITLE
Importing python modules failed from the specified python

### ISSUE THREAD

**Issue by shayandavoodii** [cjdoris/PythonCall.jl#252]
Today I installed the latest version of `PythonCall.jl` (v0.9.10) package and started with:
```julia
julia> using PythonCall

julia> ENV["JULIA_CONDAPKG_BACKEND"] = "Null"
"Null"

julia> ENV["JULIA_PYTHONCALL_EXE"] = raw"C:\Users\Shayan\AppData\Local\Programs\Python\Python310\python.exe"
"C:\\Users\\Shayan\\AppData\\Local\\Programs\\Python\\Python310\\python.exe"
```
Then I closed the Julia session and started a new one to continue. Then I failed to import the `numpy` package via `pyimport`:
```julia
julia> using PythonCall

julia> pyimport("numpy")
ERROR: Python: ModuleNotFoundError: No module named 'numpy'
Python stacktrace: none
Stacktrace:
 [1] pythrow()
   @ PythonCall C:\Users\Shayan\.julia\packages\PythonCall\3GRYN\src\err.jl:94
 [2] errcheck
   @ C:\Users\Shayan\.julia\packages\PythonCall\3GRYN\src\err.jl:10 [inlined]
 [3] pyimport(m::String)
   @ PythonCall C:\Users\Shayan\.julia\packages\PythonCall\3GRYN\src\concrete\import.jl:11
 [4] top-level scope
   @ REPL[2]:1
```
Also, I tried setting the path to the directory rather than the executable Python:
```julia
julia> ENV["JULIA_PYTHONCALL_EXE"] = raw"C:\Users\Shayan\AppData\Local\Programs\Python\Python310"
"C:\\Users\\Shayan\\AppData\\Local\\Programs\\Python\\Python310"
```
But, still, I couldn't import `numpy`. Note that I made sure that the `numpy` is installed in the specified environment:
```python
C:\Users\Shayan>pip list numpy
⋮
numpy              1.23.5
⋮
```

**Comment by cjdoris** [comment]
You need to set those env vars before you import PythonCall.

**Comment by shayandavoodii** [comment]
@cjdoris
> need to set those env vars before you import PythonCall...

Both `.../Python310` and `.../Python310/python.exe`? I guess one of these would be enough(?).

**Comment by shayandavoodii** [comment]
> You need to set those env vars before you import PythonCall, and they need to be set every time - so if you restart Julia you need to set them again.
> 
> It's usual to set these in your Julia startup file or your shell startup file if you're coming from bash/zsh/etc.

Setting the following lines into the `startup.jl` file get the job done:
```
ENV["JULIA_CONDAPKG_BACKEND"] = "Null"
ENV["JULIA_PYTHONCALL_EXE"] = raw"C:\Users\Shayan\AppData\Local\Programs\Python\Python310\python.exe"
```
```julia
julia> using PythonCall

julia> ts = pyimport("transformers")
Python _LazyModule: <module 'transformers' from 'C:\\Users\\Shayan\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\transformers\\__init__.py'>
```
Thanks. Please note to mention this precisely in the documentation as well.

**Comment by cjdoris** [comment]
> Thanks. **Please note to mention this precisely in the documentation as well.**

You're welcome. Will do!
