### ISSUE TITLE
best way to send DataFrame back to Python

### ISSUE THREAD

**Issue by mzy2240** [cjdoris/PythonCall.jl#253]
Dumb question alert: how to convert a dataframe from julia back to python? Right now I am able to get the dataframe (as a juliacall.AnyValue) in the python scope, but how to really use the data from that table? I am fine with any work around. Great tool by the way.

**Comment by cjdoris** [comment]
https://cjdoris.github.io/PythonCall.jl/stable/compat/#PythonCall.pytable

From Python, you can call `juliacall.PythonCall.pytable(your_table)`.

**Comment by mzy2240** [comment]
It works like a charm. Thank you!
