### ISSUE TITLE
How to run cell containing Python script (within Pluto)

### ISSUE THREAD

**Issue by danvinci** [cjdoris/PythonCall.jl#258]
Hi!
Thank you for this package, switching over from PyCall.

I'm using Pluto and I had a cell that had only Python code:

```
begin
py"""

from package import something

def function pyfun():
    return something()

"""
julia_funWrap = py"pyfun"
```
   

This would allow me to define several helper functions (that call other functions) all in Python, and then wrap those functions so that I can call them from Julia when needed.

Is it possible to do something similar in PythonCall?

I have a script that I'd like to reuse, the alternative being writing Julia helper functions instead, wrapping the inner calls, as well as prepare the necessary inputs so that they can be passed.

This example seems to point instead towards writing "hybrid" Python/Julia code:
https://discourse.julialang.org/t/passing-parameters-to-a-python-function-via-pycall-that-need-to-be-in-a-dict-form/84691/4

**Comment by danvinci** [comment]
**Update** 
I'm having more fun (and appreciating) rewriting the script as Julia functions, making the necessary mappings and type conversions before/after calling each wrapped (Python) function.

It would still be interesting to know if is possible to run entire Python scripts residing in a call, the documentation wasn't explicit about this.

**Comment by cjdoris** [comment]
It's possibly a bit buried, but there are functions `pyexec` and `pyeval` and macros `@pyexec` and `@pyeval` for evaluating or executing Python code.

https://cjdoris.github.io/PythonCall.jl/stable/pythoncall-reference/#PythonCall.@pyexec

Your example using PyCall can be rewritten using PythonCall as
```julia
@pyexec """
from package import something

global pyfun
def function pyfun():
    return something()
"""
julia_funWrap = @pyeval "pyfun"
```
You need `global pyfun` because `@pyexec` introduces a new local scope.

**Comment by danvinci** [comment]
Thank you!!
