### ISSUE TITLE
Extremely slow output of julia arrays in Python with juliacall

### ISSUE THREAD

**Issue by VPetukhov** [cjdoris/PythonCall.jl#263]
I'm wrapping a julia package to a python Jupyter notebook with juliacall. But the data obtained from julia can't be properly visualized in Python, as it takes really long. A minimal example below takes 19s to render if ran in console ipython (and even longer in VSCode, for whatever reason):
```python
from juliacall import Main as jl
jl.rand(10000, 1000)
```

Same goes for large DataFrames. 

Julia version 1.8.5, juliacall version 0.9.7 , python v3.8.0.

**Update**
From what I understand, the problem comes from [`pyjlany_repr`](https://github.com/cjdoris/PythonCall.jl/blob/4510da56b9cd85a3e1a2df3ba9508f4c48e83963/src/jlwrap/any.jl#L3), which calls `repr`, which interpolates the whole array into a single string:
```python
import juliacall
len(juliacall.PythonCall.repr(jl.rand(10000, 1000)))
```
>  Out[12]: 192706630

So, we get linear dependency on array size. On the other hand, calling `juliacall.PythonCall.display(jl.rand(10000, 1000))` works perfectly fine and with reasonable speed.

Is there any way to override the behavior? Honestly, I'd be even fine if we can disable input from Julia objects altogether and require them to be converted to Python first. But the current situation is extremely unfriendly to potential users of my package, as any accidental output of a julia object causes the REPL to hang without any possibility to even interrupt it...

**Comment by cjdoris** [comment]
Right now there's no override, but I'm open to changing the implementation of `__repr__` to return a truncated representation instead.

Note that `list(range(1000000))` will also print a ton of junk, so this isn't unprecedented behaviour, but I agree that the truncated output that numpy returns is nicer. Plus you can always call `jl.repr(x)` if you really want the untruncated string.

**Comment by cjdoris** [comment]
FYI you can do `jl.rand(1000,1000)._jl_display()` to display the object as you would in the Julia REPL.
