### ISSUE TITLE
Hang in IPython when loading extension

### ISSUE THREAD

**Issue by jakobnissen** [cjdoris/PythonCall.jl#268]
When I type
```
In [1]: %load_ext juliacall.ipython
```
in IPython, the REPL simply hangs. I let it sit for about 10 minutes, but nothing happened, and there was no CPU usage.
In Jupyter, the extension loads, but it does not give me access to the cell magic, see screen shot

![image](https://user-images.githubusercontent.com/23193950/218049001-3614da4f-801f-4d71-9b9d-9514551ae9f9.png)

Versions:
* Julia 1.8.5 and Julia 1.9.0-beta3 both show this
* Python 3.10.9
* PythonCall 0.9.10
* Running on Linux

**Comment by cjdoris** [comment]
OK I've looked into this. I believe there are a few things going on:
1. There was a bug in how the extension was redirecting output from Julia to the IPython kernel. This is now fixed on the main branch (you can try reinstalling juliacall direct from the repo, or wait until I make a release).
2. There was a bug in the documentation: the magic is actually called `%%julia`.
3. It looks like you have set up Jupyter to load the `juliacall.ipython` extension automatically, which is fine.

Closing as I believe this should address everything, but feel free to comment if not.
