### ISSUE TITLE
Error when calling Julia function defined in module

### ISSUE THREAD

**Issue by arbenede** [cjdoris/PythonCall.jl#27]
I am trying to call a Julia function defined in a module (say MyModule, defined in `MyModule.jl`) in a Python script. I did something along the lines of

```
from juliacall import Main as jl

jl.seval('push!(LOAD_PATH, "<path to MyModule.jl>")')
jl.seval("using MyModule")

ret = jl.MyModule.some_function(arg1,arg2,arg3)
```

however I am getting an error:

```
juliacall.Error: ArgumentError: Package MyModule not found in current path:
- Run `import Pkg; Pkg.add("MyModule")` to install the MyModule package.
```

What am I doing wrong?

**Comment by arbenede** [comment]
I am running Julia in an Ubuntu VM. I ran a few more tests. First I verified that `LOAD_PATH ` is updated correctly:
```
jl.eval('push!(LOAD_PATH, "<path to MyModule.jl>")')
jl.seval('LOAD_PATH')
<jl ["@", "@v#.#", "@stdlib", "path to MyModule.jl"]>
```

then I noticed that jl.eval and jl.seval have different behaviors:

```
>>> jl.eval("using MyModule")
'using MyModule'
```
and
```
>>> jl.seval("using MyModule")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
juliacall.Error: ArgumentError: Package MyModule not found in current path:
- Run `import Pkg; Pkg.add("MyModule")` to install the MyModule package.
```
In both cases `MyModule` is not imported:
```
>>> jl.seval('methods(MyModule.f)')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
juliacall.Error: UndefVarError: MyModule not defined
```
where `f` of course is a function defined in MyModule.

**Comment by cjdoris** [comment]
Have you checked these steps work directly in julia?

**Comment by arbenede** [comment]
Yes, in the Julia REPL everything works fine. Something I did not mention is that since I am using Julia 1.6.1 I need to to set explicitly set LD_LIBRARY_PATH before I call python3 otherwise I get an error:
```
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/julia-1.6.1/lib/julia" python3 <...>
```
I am not sure if this is relevant or not...

**Comment by cjdoris** [comment]
Can you copy in the error you get please?

**Comment by arbenede** [comment]
My bad! A pathname was wrong, as it often happens when you use a virtual machine... Thanks for you help. I am closing the issue.
