### ISSUE TITLE
overload `in(x, o::Py)` to call `o.__contains__(x)`

### ISSUE THREAD

**Issue by stevengj** [cjdoris/PythonCall.jl#279]
I just noticed that PyCall was missing an overload of `in` for `PyObject`, and I figured you might want the same for `Py`.

**Comment by stevengj** [comment]
There are a few other such methods that might be worth implementing as well: https://docs.python.org/3/library/operator.html

**Comment by cjdoris** [comment]
Already got it thanks! 🙂

https://github.com/cjdoris/PythonCall.jl/blob/ffdac16d3092a59ee83c5d0f69245d34a4c3e4dc/src/Py.jl#L337

I think all those operators which have an equivalent in Base are already there. Let me know if you spot any I've missed.
