### ISSUE TITLE
Dont use __init__

### ISSUE THREAD

**Issue by rafaqz** [cjdoris/PythonCall.jl#300]
Given recent precompilation concerns it would be better not to use and recommend using `__init__` here.

Instead pynew() could have a runtime value check, and do the import automatically on the first call?

We could pass it a string for the module name, or a closure.

**Comment by cjdoris** [comment]
Nice idea.

Would be good to investigate if adding such a check has any performance penalty, since it will be done for every

**Comment by rafaqz** [comment]
Was this actually implemented?

**Comment by cjdoris** [comment]
No, I guess I hit the Close button by mistake!

**Comment by pedromxavier** [comment]
@cjdoris is there any benchmark suite of yours? I'd like to test a few a ideas for such lazy-loading mechanism.

**Comment by cjdoris** [comment]
Just https://github.com/cjdoris/PythonCall.jl/blob/main/BENCHMARKS.md which may be out of date. Might be nice to formalise them.

**Comment by LilithHafner** [comment]
IMO this is still relevant, it should be re-opened and added to a milestone so that it is not automatically re-closed as stale.

**Comment by rafaqz** [comment]
Auto closing issues afyer 30 days doesnt really make sense, Im not going to keep pinging all my githib issues

**Comment by rafaqz** [comment]
Marking stale due to inactivity is a questionable practice. Issues that are not fixed don't just go away.

There is no chance I will work on this, it was basically a "heads up" issue for future design.

**Comment by cjdoris** [comment]
Like I said, issues which are actual issues I can label so they stick around, like I did with this one.

The bot is to close the issues that aren't actually issues - such as because it actually got resolved or the user didn't provide a way to reproduce the issue.

**Comment by rafaqz** [comment]
Issues can be closed from PRs using e.g. closes #x . Or manually if they dont matter.

Butvauto closing will end up with discussions like this - there is a reason almost no other packages do it. But your call of course.
