### ISSUE TITLE
import juliacall loads the startup.jl

### ISSUE THREAD

**Issue by mahiki** [cjdoris/PythonCall.jl#317]
**Is your feature request related to a problem? Please describe.**
I have a startup file in my local environment for REPL work. When loading packages or scripts from the command line I call julia with `julia --startup-file=no`.  There does not appear to be a way to skip the startup file in a Python repl.

**Describe the solution you'd like**
`import juliacall` should default to loading julia environment with `--startup-file=no` option.

**Describe alternatives you've considered**
I could move or rename startup.jl file so it wont be found by the julia environment.

**Additional context**
I'm developing a python application that will call a julia module to make dataframe transformations.

**Comment by cjdoris** [comment]
Good idea, I'll look into it.

**Comment by cjdoris** [comment]
You can now start Python with the option `-X juliacall-startup-file=no` to disable startup.jl. This feature will appear in the next release (our you can try it out by installing from the repo).

I'm going to leave the default as `yes` though, since that's the Julia default.

**Comment by ma-sadeghi** [comment]
@cjdoris Would you consider also adding support for an env variable to disable the startup file?

**Comment by cjdoris** [comment]
You already can, see the docs.

**Comment by ma-sadeghi** [comment]
Right, sorry I missed the docs. 
For future reference: https://juliapy.github.io/PythonCall.jl/stable/juliacall/#julia-config
