### ISSUE TITLE
How to await a python coroutine in julia

### ISSUE THREAD

**Issue by bryaan** [cjdoris/PythonCall.jl#320]
How do you await a coroutine generated by python in julia using PythonCall.jl?

This would seem to work for a future.  But what about coroutines?
```
function wait_on_py(future)
    while !Bool(future.done())
        sleep(0.1)
    end
    future
end

future |> wait_on_py
```

**Comment by cjdoris** [comment]
`asyncio.run(coro)`? https://docs.python.org/3/library/asyncio-runner.html#asyncio.run

**Comment by bryaan** [comment]
It works in python but when calling it from julia im getting an error.

```julia
import asyncio 

async def create_filter_coro(web3, fromBlock, topics):
    eventFilter = web3.eth.filter({
            "fromBlock": fromBlock,
            "topics": topics
        })
    eventFilter = await eventFilter
    return eventFilter

def create_filter_async(web3, fromBlock, topics):
    return asyncio.run(create_filter_coro(web3, fromBlock, topics))
```

```
┌ Error: 2023-06-05 23:44:06 Unexpected PyException:
│   exception =
│    Python: TypeError: object function can't be used in 'await' expression
│    Python stacktrace:
│     [1] construct_middleware
│       @ web3.middleware ~/Library/Caches/pypoetry/virtualenvs/cryptopy-5siZoxZ4-py3.10/lib/python3.10/site-packages/web3/middleware/__init__.py:130
│     [2] async_combine_middlewares
│       @ web3.middleware ~/Library/Caches/pypoetry/virtualenvs/cryptopy-5siZoxZ4-py3.10/lib/python3.10/site-packages/web3/middleware/__init__.py:119
```

**Comment by bryaan** [comment]
Again in python alone the code works.  So it must be something with this lib and async functions or types.  

The call stack points to this line:  https://github.com/ethereum/web3.py/blame/c99135587614c4f95275ea27dd3227f45ac23c73/web3/middleware/__init__.py#L130

**Comment by cjdoris** [comment]
Can you provide a full MWE of how to get to the error, and include the full error output too please.

**Comment by bryaan** [comment]
I'm going to leave this as is for now since this library doesn't really support threading.
