### ISSUE TITLE
PyCall compat mode

### ISSUE THREAD

**Issue by cjdoris** [cjdoris/PythonCall.jl#55]

**Comment by xgdgsc** [comment]
`ENV["JULIA_PYTHONCALL_EXE"] = "PYCALL"` no longer work for me. How to specify python path for now if I don' t want to use auto installed conda with python 3.10?

**Comment by cjdoris** [comment]
You can still use that environment variable to specify the Python executable.

The PyCall compat mode was removed in the last release but is back on master (`] add PythonCall#master`) if you set `ENV["JULIA_PYTHONCALL_EXE"] = "@PyCall"`.
