### ISSUE TITLE
Using PythonCall within Julia modules

### ISSUE THREAD

**Issue by haberdashPI** [cjdoris/PythonCall.jl#57]
First of all, thanks for working on this, I really appreciate these improvements from PyCall.

Seems like calling `pyimport` from the top level of a module in precompiled code would create issues.

In PyCall, the following approach is recommended:

```julia
const scipy_opt = PyNULL()

function __init__()
    copy!(scipy_opt, pyimport_conda("scipy.optimize", "scipy"))
end

end
```

I think the equivalent in PythonCall would be

```Julia
const scipy_opt = pynew()

function __init__()
   pycopy!(scipy_opt, pyimport("scipy.optimize"))
end
```

It would be worth documenting this somewhere. Obviously a lot of folks are going to be coming from PyCall (and will know to be mindful of this) but it would be better to make this fact explicit, or indicate that this isn't required.

**Comment by cjdoris** [comment]
Technically it's documented here: https://cjdoris.github.io/PythonCall.jl/dev/pythoncall/#PythonCall.pycopy!

But that's definitely buried!

The documentation could definitely do with a section on writing modules. And a section on coming from PyCall. I'll put it on my to-do list but feel free to contribute a PR.

**Comment by stevengj** [comment]
I think this is covered in the manual now?

**Comment by cjdoris** [comment]
Indeed it is.
