### ISSUE TITLE
FYI: 3.10 is out (to test) and 3.11 alpha

### ISSUE THREAD

**Issue by PallHaraldsson** [cjdoris/PythonCall.jl#63]
I didn't make a PR here to test (I do not expect failures, major changes), since failing for PyCall (premature for CI), but note there FYI on new PEP regarding new exception groups in 3.11:

https://github.com/JuliaPy/PyCall.jl/pull/928#issuecomment-945921754

**Comment by cjdoris** [comment]
Thanks for the info. I already have a ticket #54 to test on more versions of Python and Julia - but I need to write more tests first!
