### ISSUE TITLE
remove Python<3.10 restriction

### ISSUE THREAD

**Issue by cjdoris** [cjdoris/PythonCall.jl#69]
We restrict to Python<3.10 in PythonCallDeps.toml because conda appears to have issues with two-digit minor version numbers.

**Comment by PallHaraldsson** [comment]
Seeing this issue, I thought I should inform you of this Conda-compatible package I saw the other day: https://github.com/cjdoris/MicroMamba.jl

Then I realized it's your work... but at least it loads twice as fast, so you might want to substitute (Conda needs to be fixed also, or both if not already handling). Also I think you can load less-used packages conditionally,

**Comment by cjdoris** [comment]
Yep I'm working on some packages to factor out the dependency handling part of PythonCall.

**Comment by cjdoris** [comment]
Fixed now we use MicroMamba+CondaPkg.
