### ISSUE TITLE
Importing local modules

### ISSUE THREAD

**Issue by boriskaus** [cjdoris/PythonCall.jl#70]
Thanks, this appears to be a very useful package which would solve many compatibility problems between windows, linux etc.

One thing I am wondering is how to import a *local* module. In `PyCall` this would be done as:
```
const pymodule = PyNULL()
pushfirst!(PyVector(pyimport("sys")["path"]), (@__DIR__)*"/dir_relative_to_src") 
copy!(pymodule, pyimport("mylocalmodule"))
```
Help on how to do this in `PythonCall` would be highly appreciated!

**Comment by cjdoris** [comment]
Glad you like it!

The equivalent in PythonCall is:
```
const pymodule = PythonCall.pynew()
pyimport("sys").path.append("some/path")
PythonCall.pycopy!(pymodule, pyimport("mylocalmodule"))
```

**Comment by boriskaus** [comment]
Thanks, that works! See [https://github.com/JuliaGeodynamics/geomIO](https://github.com/JuliaGeodynamics/geomIO). Next up is figuring out why CI fails on windows, but works on Mac/Linux.

**Comment by kleinschmidt** [comment]
I'm following this pattern and getting occasional segfaults when I try to access the imported module (the one that I `pycopy!`ed).  Do I need to do something like GC protect that pointer so it doesn't get GCed?  Can I even do that on the julia side or do I need to do it on the python side somehow?

**Comment by kleinschmidt** [comment]
I get the same behavior FWIW when using `Ref{Py}` to store the imported module as well...

**Comment by kleinschmidt** [comment]
Wow _and_ when I `pyimport` the module afresh each time before referring to it.  I suspect this may be something specific to my module and how I'm using it!
