### ISSUE TITLE
hope support python f-string in julia

### ISSUE THREAD

**Issue by zsz00** [cjdoris/PythonCall.jl#75]
```
data = 10.1234
@py print(f"data: {data:.2f}")

data: 10.12
```

**Comment by cjdoris** [comment]
It's on the to-do list, but not very high priority. Ordinary Julia string interpolation still works though, so you can do:
```julia
julia> data = 10.1234
10.1234

julia> @py print("data = $(format(data, ".2f"))")
data = 10.12

julia> @py print("data = {:.2f}".format(data))
data = 10.12
```

**Comment by cjdoris** [comment]
BTW you should put code inside ````` ``` ````` fences to format it properly, so I've edited your post. In particular, `@py` was tagging the GitHub user called "py".

**Comment by zsz00** [comment]
I see, thank you !!
