### ISSUE TITLE
Can we use julia functions with ! postfix in python calls to julia functions

### ISSUE THREAD

**Issue by markNZed** [cjdoris/PythonCall.jl#78]
Hopefully clear in the title. It seems python does not like the ! postfix in function names and I wonder if there is a pythonic way to call a julia function with ! char e.g `jl.update!(p)` ? I guess using seval would be an option but I would like to pass in a python variable to the julia function.

**Comment by cjdoris** [comment]
As a special case, the suffix `_b` is translated to `!` so you can do `jl.update_b(p)` (b is for bang).

You could also do `getattr(jl, "update!")` or `jl.getproperty(jl, jl .Symbol("update!"))`.

**Comment by cjdoris** [comment]
Or `jl.seval("update!")(b)`.

**Comment by markNZed** [comment]
Thanks very much, that works well.
