### ISSUE TITLE
Using private Julia package SSH fails

### ISSUE THREAD

**Issue by markNZed** [cjdoris/PythonCall.jl#80]
There seems to be a bunch of issues with Julia and SSH with private packages. I'm not sure if the issues I'm seeing are specific to PythonCall.  The error I'm seeing is
```
┌ Error: Error loading PythonCall.jl
│   err = failed to clone from user@domain.com:2255/repos/ARTime.git, error: GitError(Code:ERROR, Class:SSH, Failed to retrieve list of SSH authentication methods: Failed getting response)
```
I'm not using the default .ssh/id_rsa so I enter the path to the private key when prompted. I can clone the repository using git outside of PythonCall using the SSH key.

**Comment by cjdoris** [comment]
Is the URL definitely correct? The convention is to use the suffix `.jl` on Julia package repos.

Otherwise try adding the package from the Julia REPL to see if it is an issue with PythonCall (I doubt it is).

**Comment by markNZed** [comment]
You are right that it is not PythonCall. I could reproduce the problem in the REPL. Sorry for not trying that and thanks for the suggestion. I created the repo before I learnt of the .jl convention and I think the URL is correct. The Julia creators must own GitHub stock ;)

**Comment by markNZed** [comment]
It seems there is an issue with a non-standard SSH port. The message in the REPL has swapped : for /
```
(@v1.7) pkg> add user@domain:2222/git-server/repos/ARTime.git
     Cloning git-repo `ssh://user@domain/2222/git-server/repos/ARTime.git`
```

**Comment by cjdoris** [comment]
Great glad it's working. If you think that's a bug in Julia, report it over on the Julia repo.

**Comment by markNZed** [comment]
I created https://github.com/JuliaLang/Pkg.jl/issues/2894
