### ISSUE TITLE
Should PythonCall create separate environment for different projects?

### ISSUE THREAD

**Issue by markNZed** [cjdoris/PythonCall.jl#81]
If we have two different project directories and they are pointing at different versions (or locations) of a common Julia package, then it seems this causes errors. Maybe this is just the way it is meant to work. I'm running into this issue because I have a local repo with a Julia package that I'm trying to move that to GitHub and I can't have both working in parallel with PythonCall, it seems.

**Comment by cjdoris** [comment]
It already does create separate conda environments for different Julia projects. Specifically, it creates a conda environment in the top most entry of LOAD_PATH which depends on PythonCall (and recreates it if the LOAD_PATH changes).

Can you describe the specific problem you're having? Preferably describe how I can recreate it myself.

**Comment by markNZed** [comment]
The problem might be because I'm not reinstalling the Python package when I run in the other directory. I will try to clarify this and let you know. Your answer suggests the problem is much more likely on my side than in PythonCall, thanks.

**Comment by markNZed** [comment]
Confirmed that was the issue - I was running from a different directory but Python was using an installed version of the Python package and this was causing PythonCall to see two different URLS, I guess one form the juliacalldeps.json in the installed Python package and another in the local directory where I was running. By installing the package the problem went away.
