### ISSUE TITLE
Install specific Python version

### ISSUE THREAD

**Issue by WJ-Huang** [cjdoris/PythonCall.jl#87]
Hi, thank you for this great package! When I used the package, the package installed `Python 3.10.1` by default. However, I want to install `Python 3.6` in the environment. Is it possible? I appreciate your help.

**Comment by cjdoris** [comment]
https://cjdoris.github.io/PythonCall.jl/stable/pythoncall/#python-deps

A CondaPkg.toml file like
```toml
[deps]
python = "=3.6"
```
in your project will restrict the version like you want.

Or `CondaPkg.add("python", version="=3.6")`.

**Comment by WJ-Huang** [comment]
Thank you!
