### ISSUE TITLE
Function support?

### ISSUE THREAD

**Issue by JacobNeumann88** [cjdoris/PythonCall.jl#95]
When using pyJulia if I need to write a function for julia I can write it as a string and pass it to Main.eval(). When I take a similar approach using juliaCall it simply returns a string instead of a julia function. Is there some module or command that I am missing or is this conversion not supported?
As a side note when I attempt to load a custom module using "import juliacall; jl = juliacall.newmodule('newMod')" nothing loads. I tested it using julia native modes and it loaded just fine. Are custom modules not supported?

**Comment by cjdoris** [comment]
For the first part, there is `Main.seval(...)` which parses a string then evaluates it. `Main.eval` is just the `eval` function from Julia which indeed just returns a string unchanged.

For the second part, I don't know what you mean. `newmodule` simply creates a new empty module. No code loading happens. To load a module use `jl.seval("using Example")`.
