### ISSUE TITLE
how to convert list of lists into matrix

### ISSUE THREAD

**Issue by untoreh** [cjdoris/PythonCall.jl#99]
With `PyCall` I can just do a `Matrix(data)` , but with PythonCall there doesn't seem to be a method available for converting a python list of lists into a matrix.

**Comment by cjdoris** [comment]
Good question!

One way would be something like `pyconvert(Matrix, numpy.array(data))`.

Or `pyconvert(Vector{<:Vector}, data)` gets you a vector of vectors that you can `hcat` together.
